### ISSUE TITLE
Can't add to set when dependsOnKey is true + text/html as result

### ISSUE THREAD

**Issue by petermorlion** [bymyslf/AspNetWebApi-OutputCache-Redis#1]
Hi, I'm using a slightly modified implementation of what you have here, because we're sticking to JSON.NET instead of using Jil. But in essence, I'm doing the same as you, to use Redis as a server-side caching back-end. But I'm having two issues, and was wondering wether you've encountered them too.

First, when `dependsOnKey` is true, you add the key to the set ([here](https://github.com/bymyslf/AspNetWebApi-OutputCache-Redis/blob/master/AspNetWebApi-OutputCache-Redis/AspNetWebApi-OutputCache-Redis/RedisOutputCache.cs#L52)). But when I do that, I get an exception:

    WRONGTYPE Operation against a key holding the wrong kind of value

Have you seen that?

Also, (when I comment out the failing code and) when the result is taken from the cache, it is returned as text/html instead of application/json.

I just wanted to reach out to see if you have had any similar problems. If not, feel free to close this issue.

**Comment by bymyslf** [comment]
Hi, thank you for reaching out. 

I've never seen this exception. Can you send me an example of what you're caching so I can try to help you?

**Comment by petermorlion** [comment]
Basically, it's the JSON output. But I was serializing it using JSON.NET. After having a look at [this implementation](https://gist.github.com/ianfnelson/221d1d981294774e144a), I found that we always receive a string or byte[] (see [this comment](https://gist.github.com/ianfnelson/221d1d981294774e144a#file-redisapioutputcache-cs-L68)), so it wasn't necessary to serialize. I've got it working now, but curiously, I didn't see any difference when adding or removing the code-block for `dependsOnKey`. Ie, this has no effect:

```
if (dependsOnKey != null && added)
{
    this.Redis.SetAdd(dependsOnKey, key);
}
```

Thanks for answering 👍

**Comment by bymyslf** [comment]
@petermorlion, the code-block for dependsOnKey is relevant when the library invalidates the cache. For example, content-type or etag's are stored as separate keys with a dependency to the base key (ControllerType.FullName + action) [see details here](https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/CacheOutputAttribute.cs#L246). In the cache invalidation process, the library removes all keys that starts with the base key, as you can see [here](https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/InvalidateCacheOutputAttribute.cs#L35).

If  dependsOnKey is true, the key will be added to a set and this set will be removed in the cache invalidation process.

**Comment by petermorlion** [comment]
FYI, I've implemented it differently, in a way that I have verified works for me. These are the relevant methods:

```
public void Add(string key, object o, DateTimeOffset expiration, string dependsOnKey = null)
    var redisValue = RedisValue.Null;
    var bytes = o as byte[];
    if (bytes != null)
        redisValue = bytes;
    else if (o is string)
        redisValue = (string)o;
    Db.StringSet(key, redisValue, expiration.DateTime.Subtract(DateTime.Now));
}
```

and when removing:

```
public void RemoveStartsWith(string key)
{
    var script = "redis.call('del', 'defaultKey', unpack(redis.call('keys', @pattern)))";
    var prepared = LuaScript.Prepare(script);
    var pattern = $"{key}*";
    Db.ScriptEvaluate(prepared, new { pattern = (RedisKey)pattern });
}
```

**Comment by bymyslf** [comment]
@petermorlion, great solution. When I started this project I did not consider using Lua and from there I did not continue to evolve the project. 

I'll update my project with you solution. 

Thank you for sharing.

**Comment by petermorlion** [comment]
Glad to help!
